# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-28 20:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_meetingroom_room_resource_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='meetingroom',
            name='floor',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
    ]
