# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-07-29 02:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20170728_2213'),
    ]

    operations = [
        migrations.AddField(
            model_name='presence',
            name='planned_meeting',
            field=models.BooleanField(default=False),
        ),
    ]
